import { lazy } from 'react'

export const HomePage = lazy(() => import('@/pages/HomePage'))
export const TrainingCatalogPage = lazy(() => import('@/pages/TrainingCatalogPage'))
export const TrainingDetailsPage = lazy(() => import('@/pages/TrainingDetailsPage'))
export const AboutPage = lazy(() => import('@/pages/AboutPage'))
export const TrainersPage = lazy(() => import('@/pages/TrainersPage'))
export const TestimonialsPage = lazy(() => import('@/pages/TestimonialsPage'))
export const PartnersPage = lazy(() => import('@/pages/PartnersPage'))
export const SuccessStoriesPage = lazy(() => import('@/pages/SuccessStoriesPage'))
export const EventsPage = lazy(() => import('@/pages/EventsPage'))
export const ResourcesPage = lazy(() => import('@/pages/ResourcesPage'))
export const ArticleDetailsPage = lazy(() => import('@/pages/ArticleDetailsPage'))
export const FaqPage = lazy(() => import('@/pages/FaqPage'))
export const IndustriesPage = lazy(() => import('@/pages/IndustriesPage'))
export const SolutionsForCompaniesPage = lazy(() => import('@/pages/SolutionsForCompaniesPage'))
export const RequestInformationPage = lazy(() => import('@/pages/RequestInformationPage'))
export const RequestQuotePage = lazy(() => import('@/pages/RequestQuotePage'))
export const ContactPage = lazy(() => import('@/pages/ContactPage'))
export const RegisterInterestPage = lazy(() => import('@/pages/RegisterInterestPage'))
export const ConsultationPage = lazy(() => import('@/pages/ConsultationPage'))
export const DesignSystemPreviewPage = lazy(() => import('@/pages/DesignSystemPreviewPage'))
export const NotFoundPage = lazy(() => import('@/pages/NotFoundPage'))
